#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("FluffleAndroid.Resource", IsApplication=true)]

namespace FluffleAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::HockeyApp.Resource.Color.hockeyapp_background_header = global::FluffleAndroid.Resource.Color.hockeyapp_background_header;
			global::HockeyApp.Resource.Color.hockeyapp_background_light = global::FluffleAndroid.Resource.Color.hockeyapp_background_light;
			global::HockeyApp.Resource.Color.hockeyapp_background_white = global::FluffleAndroid.Resource.Color.hockeyapp_background_white;
			global::HockeyApp.Resource.Color.hockeyapp_button_background = global::FluffleAndroid.Resource.Color.hockeyapp_button_background;
			global::HockeyApp.Resource.Color.hockeyapp_button_background_pressed = global::FluffleAndroid.Resource.Color.hockeyapp_button_background_pressed;
			global::HockeyApp.Resource.Color.hockeyapp_button_background_selected = global::FluffleAndroid.Resource.Color.hockeyapp_button_background_selected;
			global::HockeyApp.Resource.Color.hockeyapp_text_black = global::FluffleAndroid.Resource.Color.hockeyapp_text_black;
			global::HockeyApp.Resource.Color.hockeyapp_text_light = global::FluffleAndroid.Resource.Color.hockeyapp_text_light;
			global::HockeyApp.Resource.Color.hockeyapp_text_normal = global::FluffleAndroid.Resource.Color.hockeyapp_text_normal;
			global::HockeyApp.Resource.Color.hockeyapp_text_white = global::FluffleAndroid.Resource.Color.hockeyapp_text_white;
			global::HockeyApp.Resource.Drawable.hockeyapp_btn_background = global::FluffleAndroid.Resource.Drawable.hockeyapp_btn_background;
			global::HockeyApp.Resource.Id.button_add_response = global::FluffleAndroid.Resource.Id.button_add_response;
			global::HockeyApp.Resource.Id.button_attachment = global::FluffleAndroid.Resource.Id.button_attachment;
			global::HockeyApp.Resource.Id.button_login = global::FluffleAndroid.Resource.Id.button_login;
			global::HockeyApp.Resource.Id.button_refresh = global::FluffleAndroid.Resource.Id.button_refresh;
			global::HockeyApp.Resource.Id.button_send = global::FluffleAndroid.Resource.Id.button_send;
			global::HockeyApp.Resource.Id.button_update = global::FluffleAndroid.Resource.Id.button_update;
			global::HockeyApp.Resource.Id.input_email = global::FluffleAndroid.Resource.Id.input_email;
			global::HockeyApp.Resource.Id.input_message = global::FluffleAndroid.Resource.Id.input_message;
			global::HockeyApp.Resource.Id.input_name = global::FluffleAndroid.Resource.Id.input_name;
			global::HockeyApp.Resource.Id.input_password = global::FluffleAndroid.Resource.Id.input_password;
			global::HockeyApp.Resource.Id.input_subject = global::FluffleAndroid.Resource.Id.input_subject;
			global::HockeyApp.Resource.Id.label_author = global::FluffleAndroid.Resource.Id.label_author;
			global::HockeyApp.Resource.Id.label_date = global::FluffleAndroid.Resource.Id.label_date;
			global::HockeyApp.Resource.Id.label_last_updated = global::FluffleAndroid.Resource.Id.label_last_updated;
			global::HockeyApp.Resource.Id.label_message = global::FluffleAndroid.Resource.Id.label_message;
			global::HockeyApp.Resource.Id.label_text = global::FluffleAndroid.Resource.Id.label_text;
			global::HockeyApp.Resource.Id.label_title = global::FluffleAndroid.Resource.Id.label_title;
			global::HockeyApp.Resource.Id.label_version = global::FluffleAndroid.Resource.Id.label_version;
			global::HockeyApp.Resource.Id.list_attachments = global::FluffleAndroid.Resource.Id.list_attachments;
			global::HockeyApp.Resource.Id.list_feedback_messages = global::FluffleAndroid.Resource.Id.list_feedback_messages;
			global::HockeyApp.Resource.Id.text_headline = global::FluffleAndroid.Resource.Id.text_headline;
			global::HockeyApp.Resource.Id.view_header = global::FluffleAndroid.Resource.Id.view_header;
			global::HockeyApp.Resource.Id.web_update_details = global::FluffleAndroid.Resource.Id.web_update_details;
			global::HockeyApp.Resource.Id.wrapper_attachments = global::FluffleAndroid.Resource.Id.wrapper_attachments;
			global::HockeyApp.Resource.Id.wrapper_feedback = global::FluffleAndroid.Resource.Id.wrapper_feedback;
			global::HockeyApp.Resource.Id.wrapper_feedback_scroll = global::FluffleAndroid.Resource.Id.wrapper_feedback_scroll;
			global::HockeyApp.Resource.Id.wrapper_messages = global::FluffleAndroid.Resource.Id.wrapper_messages;
			global::HockeyApp.Resource.Id.wrapper_messages_buttons = global::FluffleAndroid.Resource.Id.wrapper_messages_buttons;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_expiry_info = global::FluffleAndroid.Resource.Layout.hockeyapp_activity_expiry_info;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_feedback = global::FluffleAndroid.Resource.Layout.hockeyapp_activity_feedback;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_login = global::FluffleAndroid.Resource.Layout.hockeyapp_activity_login;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_update = global::FluffleAndroid.Resource.Layout.hockeyapp_activity_update;
			global::HockeyApp.Resource.Layout.hockeyapp_fragment_update = global::FluffleAndroid.Resource.Layout.hockeyapp_fragment_update;
			global::HockeyApp.Resource.Layout.hockeyapp_view_feedback_message = global::FluffleAndroid.Resource.Layout.hockeyapp_view_feedback_message;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_app_name_fallback = global::FluffleAndroid.Resource.String.hockeyapp_crash_dialog_app_name_fallback;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_message = global::FluffleAndroid.Resource.String.hockeyapp_crash_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_negative_button = global::FluffleAndroid.Resource.String.hockeyapp_crash_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_neutral_button = global::FluffleAndroid.Resource.String.hockeyapp_crash_dialog_neutral_button;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_positive_button = global::FluffleAndroid.Resource.String.hockeyapp_crash_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_title = global::FluffleAndroid.Resource.String.hockeyapp_crash_dialog_title;
			global::HockeyApp.Resource.String.hockeyapp_dialog_error_message = global::FluffleAndroid.Resource.String.hockeyapp_dialog_error_message;
			global::HockeyApp.Resource.String.hockeyapp_dialog_error_title = global::FluffleAndroid.Resource.String.hockeyapp_dialog_error_title;
			global::HockeyApp.Resource.String.hockeyapp_dialog_negative_button = global::FluffleAndroid.Resource.String.hockeyapp_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_dialog_positive_button = global::FluffleAndroid.Resource.String.hockeyapp_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_message = global::FluffleAndroid.Resource.String.hockeyapp_download_failed_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_negative_button = global::FluffleAndroid.Resource.String.hockeyapp_download_failed_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_positive_button = global::FluffleAndroid.Resource.String.hockeyapp_download_failed_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_title = global::FluffleAndroid.Resource.String.hockeyapp_download_failed_dialog_title;
			global::HockeyApp.Resource.String.hockeyapp_error_no_network_message = global::FluffleAndroid.Resource.String.hockeyapp_error_no_network_message;
			global::HockeyApp.Resource.String.hockeyapp_expiry_info_text = global::FluffleAndroid.Resource.String.hockeyapp_expiry_info_text;
			global::HockeyApp.Resource.String.hockeyapp_expiry_info_title = global::FluffleAndroid.Resource.String.hockeyapp_expiry_info_title;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attach_file = global::FluffleAndroid.Resource.String.hockeyapp_feedback_attach_file;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attach_picture = global::FluffleAndroid.Resource.String.hockeyapp_feedback_attach_picture;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_button_text = global::FluffleAndroid.Resource.String.hockeyapp_feedback_attachment_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_error = global::FluffleAndroid.Resource.String.hockeyapp_feedback_attachment_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_loading = global::FluffleAndroid.Resource.String.hockeyapp_feedback_attachment_loading;
			global::HockeyApp.Resource.String.hockeyapp_feedback_email_hint = global::FluffleAndroid.Resource.String.hockeyapp_feedback_email_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_failed_text = global::FluffleAndroid.Resource.String.hockeyapp_feedback_failed_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_failed_title = global::FluffleAndroid.Resource.String.hockeyapp_feedback_failed_title;
			global::HockeyApp.Resource.String.hockeyapp_feedback_fetching_feedback_text = global::FluffleAndroid.Resource.String.hockeyapp_feedback_fetching_feedback_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_generic_error = global::FluffleAndroid.Resource.String.hockeyapp_feedback_generic_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_last_updated_text = global::FluffleAndroid.Resource.String.hockeyapp_feedback_last_updated_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_max_attachments_allowed = global::FluffleAndroid.Resource.String.hockeyapp_feedback_max_attachments_allowed;
			global::HockeyApp.Resource.String.hockeyapp_feedback_message_hint = global::FluffleAndroid.Resource.String.hockeyapp_feedback_message_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_name_hint = global::FluffleAndroid.Resource.String.hockeyapp_feedback_name_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_refresh_button_text = global::FluffleAndroid.Resource.String.hockeyapp_feedback_refresh_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_response_button_text = global::FluffleAndroid.Resource.String.hockeyapp_feedback_response_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_select_file = global::FluffleAndroid.Resource.String.hockeyapp_feedback_select_file;
			global::HockeyApp.Resource.String.hockeyapp_feedback_select_picture = global::FluffleAndroid.Resource.String.hockeyapp_feedback_select_picture;
			global::HockeyApp.Resource.String.hockeyapp_feedback_send_button_text = global::FluffleAndroid.Resource.String.hockeyapp_feedback_send_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_send_generic_error = global::FluffleAndroid.Resource.String.hockeyapp_feedback_send_generic_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_send_network_error = global::FluffleAndroid.Resource.String.hockeyapp_feedback_send_network_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_sending_feedback_text = global::FluffleAndroid.Resource.String.hockeyapp_feedback_sending_feedback_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_subject_hint = global::FluffleAndroid.Resource.String.hockeyapp_feedback_subject_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_title = global::FluffleAndroid.Resource.String.hockeyapp_feedback_title;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_email_empty = global::FluffleAndroid.Resource.String.hockeyapp_feedback_validate_email_empty;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_email_error = global::FluffleAndroid.Resource.String.hockeyapp_feedback_validate_email_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_name_error = global::FluffleAndroid.Resource.String.hockeyapp_feedback_validate_name_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_subject_error = global::FluffleAndroid.Resource.String.hockeyapp_feedback_validate_subject_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_text_error = global::FluffleAndroid.Resource.String.hockeyapp_feedback_validate_text_error;
			global::HockeyApp.Resource.String.hockeyapp_login_email_hint = global::FluffleAndroid.Resource.String.hockeyapp_login_email_hint;
			global::HockeyApp.Resource.String.hockeyapp_login_headline_text = global::FluffleAndroid.Resource.String.hockeyapp_login_headline_text;
			global::HockeyApp.Resource.String.hockeyapp_login_headline_text_email_only = global::FluffleAndroid.Resource.String.hockeyapp_login_headline_text_email_only;
			global::HockeyApp.Resource.String.hockeyapp_login_login_button_text = global::FluffleAndroid.Resource.String.hockeyapp_login_login_button_text;
			global::HockeyApp.Resource.String.hockeyapp_login_missing_credentials_toast = global::FluffleAndroid.Resource.String.hockeyapp_login_missing_credentials_toast;
			global::HockeyApp.Resource.String.hockeyapp_login_password_hint = global::FluffleAndroid.Resource.String.hockeyapp_login_password_hint;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_message = global::FluffleAndroid.Resource.String.hockeyapp_paint_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_negative_button = global::FluffleAndroid.Resource.String.hockeyapp_paint_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_neutral_button = global::FluffleAndroid.Resource.String.hockeyapp_paint_dialog_neutral_button;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_positive_button = global::FluffleAndroid.Resource.String.hockeyapp_paint_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_paint_indicator_toast = global::FluffleAndroid.Resource.String.hockeyapp_paint_indicator_toast;
			global::HockeyApp.Resource.String.hockeyapp_paint_menu_clear = global::FluffleAndroid.Resource.String.hockeyapp_paint_menu_clear;
			global::HockeyApp.Resource.String.hockeyapp_paint_menu_save = global::FluffleAndroid.Resource.String.hockeyapp_paint_menu_save;
			global::HockeyApp.Resource.String.hockeyapp_paint_menu_undo = global::FluffleAndroid.Resource.String.hockeyapp_paint_menu_undo;
			global::HockeyApp.Resource.String.hockeyapp_permission_dialog_negative_button = global::FluffleAndroid.Resource.String.hockeyapp_permission_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_permission_dialog_positive_button = global::FluffleAndroid.Resource.String.hockeyapp_permission_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_permission_update_message = global::FluffleAndroid.Resource.String.hockeyapp_permission_update_message;
			global::HockeyApp.Resource.String.hockeyapp_permission_update_title = global::FluffleAndroid.Resource.String.hockeyapp_permission_update_title;
			global::HockeyApp.Resource.String.hockeyapp_update_button = global::FluffleAndroid.Resource.String.hockeyapp_update_button;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_message = global::FluffleAndroid.Resource.String.hockeyapp_update_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_negative_button = global::FluffleAndroid.Resource.String.hockeyapp_update_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_positive_button = global::FluffleAndroid.Resource.String.hockeyapp_update_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_title = global::FluffleAndroid.Resource.String.hockeyapp_update_dialog_title;
			global::HockeyApp.Resource.String.hockeyapp_update_mandatory_toast = global::FluffleAndroid.Resource.String.hockeyapp_update_mandatory_toast;
			global::HockeyApp.Resource.String.hockeyapp_update_version_details_label = global::FluffleAndroid.Resource.String.hockeyapp_update_version_details_label;
			global::HockeyApp.Resource.String.library_name = global::FluffleAndroid.Resource.String.library_name;
			global::HockeyApp.Resource.Style.HockeyApp_ButtonStyle = global::FluffleAndroid.Resource.Style.HockeyApp_ButtonStyle;
			global::HockeyApp.Resource.Style.HockeyApp_EditTextStyle = global::FluffleAndroid.Resource.Style.HockeyApp_EditTextStyle;
			global::HockeyApp.Resource.Style.HockeyApp_SingleLineInputStyle = global::FluffleAndroid.Resource.Style.HockeyApp_SingleLineInputStyle;
			global::com.refractored.Resource.Attribute.pstsDividerColor = global::FluffleAndroid.Resource.Attribute.pstsDividerColor;
			global::com.refractored.Resource.Attribute.pstsDividerPadding = global::FluffleAndroid.Resource.Attribute.pstsDividerPadding;
			global::com.refractored.Resource.Attribute.pstsDividerWidth = global::FluffleAndroid.Resource.Attribute.pstsDividerWidth;
			global::com.refractored.Resource.Attribute.pstsIndicatorColor = global::FluffleAndroid.Resource.Attribute.pstsIndicatorColor;
			global::com.refractored.Resource.Attribute.pstsIndicatorHeight = global::FluffleAndroid.Resource.Attribute.pstsIndicatorHeight;
			global::com.refractored.Resource.Attribute.pstsPaddingMiddle = global::FluffleAndroid.Resource.Attribute.pstsPaddingMiddle;
			global::com.refractored.Resource.Attribute.pstsScrollOffset = global::FluffleAndroid.Resource.Attribute.pstsScrollOffset;
			global::com.refractored.Resource.Attribute.pstsShouldExpand = global::FluffleAndroid.Resource.Attribute.pstsShouldExpand;
			global::com.refractored.Resource.Attribute.pstsTabBackground = global::FluffleAndroid.Resource.Attribute.pstsTabBackground;
			global::com.refractored.Resource.Attribute.pstsTabPaddingLeftRight = global::FluffleAndroid.Resource.Attribute.pstsTabPaddingLeftRight;
			global::com.refractored.Resource.Attribute.pstsTextAllCaps = global::FluffleAndroid.Resource.Attribute.pstsTextAllCaps;
			global::com.refractored.Resource.Attribute.pstsTextAlpha = global::FluffleAndroid.Resource.Attribute.pstsTextAlpha;
			global::com.refractored.Resource.Attribute.pstsTextColorSelected = global::FluffleAndroid.Resource.Attribute.pstsTextColorSelected;
			global::com.refractored.Resource.Attribute.pstsTextSelectedStyle = global::FluffleAndroid.Resource.Attribute.pstsTextSelectedStyle;
			global::com.refractored.Resource.Attribute.pstsTextStyle = global::FluffleAndroid.Resource.Attribute.pstsTextStyle;
			global::com.refractored.Resource.Attribute.pstsUnderlineColor = global::FluffleAndroid.Resource.Attribute.pstsUnderlineColor;
			global::com.refractored.Resource.Attribute.pstsUnderlineHeight = global::FluffleAndroid.Resource.Attribute.pstsUnderlineHeight;
			global::com.refractored.Resource.Color.psts_background_tab_pressed = global::FluffleAndroid.Resource.Color.psts_background_tab_pressed;
			global::com.refractored.Resource.Drawable.psts_background_tab = global::FluffleAndroid.Resource.Drawable.psts_background_tab;
			global::com.refractored.Resource.Id.bold = global::FluffleAndroid.Resource.Id.bold;
			global::com.refractored.Resource.Id.italic = global::FluffleAndroid.Resource.Id.italic;
			global::com.refractored.Resource.Id.normal = global::FluffleAndroid.Resource.Id.normal;
			global::com.refractored.Resource.Id.psts_tab_title = global::FluffleAndroid.Resource.Id.psts_tab_title;
			global::com.refractored.Resource.Layout.psts_tab = global::FluffleAndroid.Resource.Layout.psts_tab;
			global::com.refractored.Resource.Styleable.PagerSlidingTabStrip = global::FluffleAndroid.Resource.Styleable.PagerSlidingTabStrip;
			global::com.refractored.Resource.Styleable.PagerSlidingTabStrip_pstsDividerColor = global::FluffleAndroid.Resource.Styleable.PagerSlidingTabStrip_pstsDividerColor;
			global::com.refractored.Resource.Styleable.PagerSlidingTabStrip_pstsDividerPadding = global::FluffleAndroid.Resource.Styleable.PagerSlidingTabStrip_pstsDividerPadding;
			global::com.refractored.Resource.Styleable.PagerSlidingTabStrip_pstsDividerWidth = global::FluffleAndroid.Resource.Styleable.PagerSlidingTabStrip_pstsDividerWidth;
			global::com.refractored.Resource.Styleable.PagerSlidingTabStrip_pstsIndicatorColor = global::FluffleAndroid.Resource.Styleable.PagerSlidingTabStrip_pstsIndicatorColor;
			global::com.refractored.Resource.Styleable.PagerSlidingTabStrip_pstsIndicatorHeight = global::FluffleAndroid.Resource.Styleable.PagerSlidingTabStrip_pstsIndicatorHeight;
			global::com.refractored.Resource.Styleable.PagerSlidingTabStrip_pstsPaddingMiddle = global::FluffleAndroid.Resource.Styleable.PagerSlidingTabStrip_pstsPaddingMiddle;
			global::com.refractored.Resource.Styleable.PagerSlidingTabStrip_pstsScrollOffset = global::FluffleAndroid.Resource.Styleable.PagerSlidingTabStrip_pstsScrollOffset;
			global::com.refractored.Resource.Styleable.PagerSlidingTabStrip_pstsShouldExpand = global::FluffleAndroid.Resource.Styleable.PagerSlidingTabStrip_pstsShouldExpand;
			global::com.refractored.Resource.Styleable.PagerSlidingTabStrip_pstsTabBackground = global::FluffleAndroid.Resource.Styleable.PagerSlidingTabStrip_pstsTabBackground;
			global::com.refractored.Resource.Styleable.PagerSlidingTabStrip_pstsTabPaddingLeftRight = global::FluffleAndroid.Resource.Styleable.PagerSlidingTabStrip_pstsTabPaddingLeftRight;
			global::com.refractored.Resource.Styleable.PagerSlidingTabStrip_pstsTextAllCaps = global::FluffleAndroid.Resource.Styleable.PagerSlidingTabStrip_pstsTextAllCaps;
			global::com.refractored.Resource.Styleable.PagerSlidingTabStrip_pstsTextAlpha = global::FluffleAndroid.Resource.Styleable.PagerSlidingTabStrip_pstsTextAlpha;
			global::com.refractored.Resource.Styleable.PagerSlidingTabStrip_pstsTextColorSelected = global::FluffleAndroid.Resource.Styleable.PagerSlidingTabStrip_pstsTextColorSelected;
			global::com.refractored.Resource.Styleable.PagerSlidingTabStrip_pstsTextSelectedStyle = global::FluffleAndroid.Resource.Styleable.PagerSlidingTabStrip_pstsTextSelectedStyle;
			global::com.refractored.Resource.Styleable.PagerSlidingTabStrip_pstsTextStyle = global::FluffleAndroid.Resource.Styleable.PagerSlidingTabStrip_pstsTextStyle;
			global::com.refractored.Resource.Styleable.PagerSlidingTabStrip_pstsUnderlineColor = global::FluffleAndroid.Resource.Styleable.PagerSlidingTabStrip_pstsUnderlineColor;
			global::com.refractored.Resource.Styleable.PagerSlidingTabStrip_pstsUnderlineHeight = global::FluffleAndroid.Resource.Styleable.PagerSlidingTabStrip_pstsUnderlineHeight;
			global::ZXing.Mobile.Resource.Id.contentFrame = global::FluffleAndroid.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::FluffleAndroid.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::FluffleAndroid.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int pstsDividerColor = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int pstsDividerPadding = 2130771974;
			
			// aapt resource value: 0x7f010003
			public const int pstsDividerWidth = 2130771971;
			
			// aapt resource value: 0x7f010000
			public const int pstsIndicatorColor = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int pstsIndicatorHeight = 2130771972;
			
			// aapt resource value: 0x7f01000c
			public const int pstsPaddingMiddle = 2130771980;
			
			// aapt resource value: 0x7f010008
			public const int pstsScrollOffset = 2130771976;
			
			// aapt resource value: 0x7f01000a
			public const int pstsShouldExpand = 2130771978;
			
			// aapt resource value: 0x7f010009
			public const int pstsTabBackground = 2130771977;
			
			// aapt resource value: 0x7f010007
			public const int pstsTabPaddingLeftRight = 2130771975;
			
			// aapt resource value: 0x7f01000b
			public const int pstsTextAllCaps = 2130771979;
			
			// aapt resource value: 0x7f01000e
			public const int pstsTextAlpha = 2130771982;
			
			// aapt resource value: 0x7f01000d
			public const int pstsTextColorSelected = 2130771981;
			
			// aapt resource value: 0x7f010010
			public const int pstsTextSelectedStyle = 2130771984;
			
			// aapt resource value: 0x7f01000f
			public const int pstsTextStyle = 2130771983;
			
			// aapt resource value: 0x7f010001
			public const int pstsUnderlineColor = 2130771969;
			
			// aapt resource value: 0x7f010005
			public const int pstsUnderlineHeight = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050001
			public const int hockeyapp_background_header = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int hockeyapp_background_light = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int hockeyapp_background_white = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int hockeyapp_button_background = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int hockeyapp_button_background_pressed = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int hockeyapp_button_background_selected = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int hockeyapp_text_black = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int hockeyapp_text_light = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int hockeyapp_text_normal = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int hockeyapp_text_white = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int psts_background_tab_pressed = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int hockeyapp_btn_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int psts_background_tab = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int bold = 2131230720;
			
			// aapt resource value: 0x7f080010
			public const int button_add_response = 2131230736;
			
			// aapt resource value: 0x7f08000b
			public const int button_attachment = 2131230731;
			
			// aapt resource value: 0x7f080015
			public const int button_login = 2131230741;
			
			// aapt resource value: 0x7f080011
			public const int button_refresh = 2131230737;
			
			// aapt resource value: 0x7f08000c
			public const int button_send = 2131230732;
			
			// aapt resource value: 0x7f080019
			public const int button_update = 2131230745;
			
			// aapt resource value: 0x7f080021
			public const int contentFrame = 2131230753;
			
			// aapt resource value: 0x7f080007
			public const int input_email = 2131230727;
			
			// aapt resource value: 0x7f080009
			public const int input_message = 2131230729;
			
			// aapt resource value: 0x7f080006
			public const int input_name = 2131230726;
			
			// aapt resource value: 0x7f080014
			public const int input_password = 2131230740;
			
			// aapt resource value: 0x7f080008
			public const int input_subject = 2131230728;
			
			// aapt resource value: 0x7f080001
			public const int italic = 2131230721;
			
			// aapt resource value: 0x7f08001b
			public const int label_author = 2131230747;
			
			// aapt resource value: 0x7f08001c
			public const int label_date = 2131230748;
			
			// aapt resource value: 0x7f08000e
			public const int label_last_updated = 2131230734;
			
			// aapt resource value: 0x7f080003
			public const int label_message = 2131230723;
			
			// aapt resource value: 0x7f08001d
			public const int label_text = 2131230749;
			
			// aapt resource value: 0x7f080017
			public const int label_title = 2131230743;
			
			// aapt resource value: 0x7f080018
			public const int label_version = 2131230744;
			
			// aapt resource value: 0x7f08001e
			public const int list_attachments = 2131230750;
			
			// aapt resource value: 0x7f080012
			public const int list_feedback_messages = 2131230738;
			
			// aapt resource value: 0x7f08001f
			public const int myButton = 2131230751;
			
			// aapt resource value: 0x7f080002
			public const int normal = 2131230722;
			
			// aapt resource value: 0x7f080020
			public const int psts_tab_title = 2131230752;
			
			// aapt resource value: 0x7f080013
			public const int text_headline = 2131230739;
			
			// aapt resource value: 0x7f080016
			public const int view_header = 2131230742;
			
			// aapt resource value: 0x7f08001a
			public const int web_update_details = 2131230746;
			
			// aapt resource value: 0x7f08000a
			public const int wrapper_attachments = 2131230730;
			
			// aapt resource value: 0x7f080005
			public const int wrapper_feedback = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int wrapper_feedback_scroll = 2131230724;
			
			// aapt resource value: 0x7f08000d
			public const int wrapper_messages = 2131230733;
			
			// aapt resource value: 0x7f08000f
			public const int wrapper_messages_buttons = 2131230735;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int hockeyapp_activity_expiry_info = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int hockeyapp_activity_feedback = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int hockeyapp_activity_login = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int hockeyapp_activity_update = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int hockeyapp_fragment_update = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int hockeyapp_view_feedback_message = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int Main = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int psts_tab = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int zxingscanneractivitylayout = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int zxingscannerfragmentlayout = 2130968585;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060049
			public const int app_name = 2131099721;
			
			// aapt resource value: 0x7f060048
			public const int hello = 2131099720;
			
			// aapt resource value: 0x7f060000
			public const int hockeyapp_crash_dialog_app_name_fallback = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int hockeyapp_crash_dialog_message = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int hockeyapp_crash_dialog_negative_button = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int hockeyapp_crash_dialog_neutral_button = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int hockeyapp_crash_dialog_positive_button = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int hockeyapp_crash_dialog_title = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int hockeyapp_dialog_error_message = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int hockeyapp_dialog_error_title = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int hockeyapp_dialog_negative_button = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int hockeyapp_dialog_positive_button = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int hockeyapp_download_failed_dialog_message = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int hockeyapp_download_failed_dialog_negative_button = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int hockeyapp_download_failed_dialog_positive_button = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int hockeyapp_download_failed_dialog_title = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int hockeyapp_error_no_network_message = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int hockeyapp_expiry_info_text = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int hockeyapp_expiry_info_title = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int hockeyapp_feedback_attach_file = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int hockeyapp_feedback_attach_picture = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int hockeyapp_feedback_attachment_button_text = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int hockeyapp_feedback_attachment_error = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int hockeyapp_feedback_attachment_loading = 2131099669;
			
			// aapt resource value: 0x7f060016
			public const int hockeyapp_feedback_email_hint = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int hockeyapp_feedback_failed_text = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int hockeyapp_feedback_failed_title = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int hockeyapp_feedback_fetching_feedback_text = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int hockeyapp_feedback_generic_error = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int hockeyapp_feedback_last_updated_text = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int hockeyapp_feedback_max_attachments_allowed = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int hockeyapp_feedback_message_hint = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int hockeyapp_feedback_name_hint = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int hockeyapp_feedback_refresh_button_text = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int hockeyapp_feedback_response_button_text = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int hockeyapp_feedback_select_file = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int hockeyapp_feedback_select_picture = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int hockeyapp_feedback_send_button_text = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int hockeyapp_feedback_send_generic_error = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int hockeyapp_feedback_send_network_error = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int hockeyapp_feedback_sending_feedback_text = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int hockeyapp_feedback_subject_hint = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int hockeyapp_feedback_title = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int hockeyapp_feedback_validate_email_empty = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int hockeyapp_feedback_validate_email_error = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int hockeyapp_feedback_validate_name_error = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int hockeyapp_feedback_validate_subject_error = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int hockeyapp_feedback_validate_text_error = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int hockeyapp_login_email_hint = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int hockeyapp_login_headline_text = 2131099695;
			
			// aapt resource value: 0x7f060030
			public const int hockeyapp_login_headline_text_email_only = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int hockeyapp_login_login_button_text = 2131099697;
			
			// aapt resource value: 0x7f060032
			public const int hockeyapp_login_missing_credentials_toast = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int hockeyapp_login_password_hint = 2131099699;
			
			// aapt resource value: 0x7f060034
			public const int hockeyapp_paint_dialog_message = 2131099700;
			
			// aapt resource value: 0x7f060035
			public const int hockeyapp_paint_dialog_negative_button = 2131099701;
			
			// aapt resource value: 0x7f060036
			public const int hockeyapp_paint_dialog_neutral_button = 2131099702;
			
			// aapt resource value: 0x7f060037
			public const int hockeyapp_paint_dialog_positive_button = 2131099703;
			
			// aapt resource value: 0x7f060038
			public const int hockeyapp_paint_indicator_toast = 2131099704;
			
			// aapt resource value: 0x7f060039
			public const int hockeyapp_paint_menu_clear = 2131099705;
			
			// aapt resource value: 0x7f06003a
			public const int hockeyapp_paint_menu_save = 2131099706;
			
			// aapt resource value: 0x7f06003b
			public const int hockeyapp_paint_menu_undo = 2131099707;
			
			// aapt resource value: 0x7f06003c
			public const int hockeyapp_permission_dialog_negative_button = 2131099708;
			
			// aapt resource value: 0x7f06003d
			public const int hockeyapp_permission_dialog_positive_button = 2131099709;
			
			// aapt resource value: 0x7f06003e
			public const int hockeyapp_permission_update_message = 2131099710;
			
			// aapt resource value: 0x7f06003f
			public const int hockeyapp_permission_update_title = 2131099711;
			
			// aapt resource value: 0x7f060040
			public const int hockeyapp_update_button = 2131099712;
			
			// aapt resource value: 0x7f060041
			public const int hockeyapp_update_dialog_message = 2131099713;
			
			// aapt resource value: 0x7f060042
			public const int hockeyapp_update_dialog_negative_button = 2131099714;
			
			// aapt resource value: 0x7f060043
			public const int hockeyapp_update_dialog_positive_button = 2131099715;
			
			// aapt resource value: 0x7f060044
			public const int hockeyapp_update_dialog_title = 2131099716;
			
			// aapt resource value: 0x7f060045
			public const int hockeyapp_update_mandatory_toast = 2131099717;
			
			// aapt resource value: 0x7f060046
			public const int hockeyapp_update_version_details_label = 2131099718;
			
			// aapt resource value: 0x7f060047
			public const int library_name = 2131099719;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int HockeyApp_ButtonStyle = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int HockeyApp_EditTextStyle = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int HockeyApp_SingleLineInputStyle = 2131165186;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] PagerSlidingTabStrip = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 2
			public const int PagerSlidingTabStrip_pstsDividerColor = 2;
			
			// aapt resource value: 6
			public const int PagerSlidingTabStrip_pstsDividerPadding = 6;
			
			// aapt resource value: 3
			public const int PagerSlidingTabStrip_pstsDividerWidth = 3;
			
			// aapt resource value: 0
			public const int PagerSlidingTabStrip_pstsIndicatorColor = 0;
			
			// aapt resource value: 4
			public const int PagerSlidingTabStrip_pstsIndicatorHeight = 4;
			
			// aapt resource value: 12
			public const int PagerSlidingTabStrip_pstsPaddingMiddle = 12;
			
			// aapt resource value: 8
			public const int PagerSlidingTabStrip_pstsScrollOffset = 8;
			
			// aapt resource value: 10
			public const int PagerSlidingTabStrip_pstsShouldExpand = 10;
			
			// aapt resource value: 9
			public const int PagerSlidingTabStrip_pstsTabBackground = 9;
			
			// aapt resource value: 7
			public const int PagerSlidingTabStrip_pstsTabPaddingLeftRight = 7;
			
			// aapt resource value: 11
			public const int PagerSlidingTabStrip_pstsTextAllCaps = 11;
			
			// aapt resource value: 14
			public const int PagerSlidingTabStrip_pstsTextAlpha = 14;
			
			// aapt resource value: 13
			public const int PagerSlidingTabStrip_pstsTextColorSelected = 13;
			
			// aapt resource value: 16
			public const int PagerSlidingTabStrip_pstsTextSelectedStyle = 16;
			
			// aapt resource value: 15
			public const int PagerSlidingTabStrip_pstsTextStyle = 15;
			
			// aapt resource value: 1
			public const int PagerSlidingTabStrip_pstsUnderlineColor = 1;
			
			// aapt resource value: 5
			public const int PagerSlidingTabStrip_pstsUnderlineHeight = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
